### ISSUE TITLE
Are there any code examples available?

### ISSUE THREAD

**Issue by benyamindsmith** [8bitcynic/dap#1]
I found this repository by googling for a open source SAS compiler to use as a engine for [writing SAS codes in RMarkdown](https://www.ssc.wisc.edu/~hemken/SASworkshops/Markdown/SASmdpackage.html) and am wondering before cloning to my machine if there are any examples of writing and compiling SAS codes? 

Do I just make a .sas file with the relevant codes and run it accordingly in the terminal? 

Thanks!

**Comment by 8bitcynic** [comment]
Hello @benyamindsmith , within the dap directory, there is an examples folder which contains some code that might be of assistance to you. This examples folder is currently used as a test suite. You are correct in that you would just need to make a .sas file with the relevant codes. You would just need to type "dap" on your command line after you have compiled the machine with your corresponding .sas file. 

That being said, while dap is compatible with SAS there are quite a few pieces missing such as:
- proper do loops
- Macros
- datalines/cards
- And quite a few missing procedures. 

These items are in the works, but the pace on my part is slow going. 
If you have a procedure you want to implement per your usage of the system within RMarkdown, feel free to make a pull request. 
Thank you for your question! 
8bitcynic
